### ISSUE TITLE
XML-tagged structs operation

### ISSUE THREAD

**Issue by suntong** [ChrisTrenkamp/goxpath#4]
Logging [from here](https://www.reddit.com/r/golang/comments/410x66/looking_for_feedback_for_my_xpath_implementation/). 

> I'm also looking for some ideas on extending the parser to operate on XML-tagged structs.

Quite agree. 

Maybe implementing [Python ElementTree module XML API](https://docs.python.org/2/library/xml.etree.elementtree.html) as the starting point? 

Thanks again for the great work!

**Comment by ChrisTrenkamp** [comment]
I've changed priorities since that post to making the XPath parser compliant with the 1.0 specification, and it's pretty much there with a couple exceptions.  The next thing goxpath really needs before anything else is documentation and a go-generate program needs to be written for a standard test suite for custom tree's, not just the default tree/xmltree package.

After that, I can start writing a custom tree for XML-tagged structs.  The advantage with goxpath's design is it works with the interfaces defined in the tree package.  tree/xmltree is just a default implementation.  This means you can write your own tree if you have some special needs, or if you want to work with some other format like HTML, JSON, or structs (though lets keep it limited to XML tags).  However, the disadvantage with this design is it can get tricky to implement the tree properly without breaking some part of the spec, like node positions or namespaces.  Also, specifically for structs, reflection would have to be used, so performance would take a big hit.

That python module is more like Java's DOM object model, which is good for adding and removing elements in the tree, but takes a lot of memory.  A tree can be created for that kind of functionality, but I don't have any need for that.  The xmltree package was meant to be lean and non-volatile.

If anything the encoding/xml package should be used as a starting point to see how the Go maintainers handle XML tags.  It won't be an easy project to pull off, but I think it can be done.  I like a challenge.

**Comment by suntong** [comment]
Gotya.

**Comment by suntong** [comment]
Good to see you working on it again. 

> some of the design goals:
>
> - Provide a flexible-enough API so you can write your own functions in XPath expressions.
- Abstract the tree to an interface so that not only can XML documents be parsed, but other document types as well.  Since I started this project, I've been wanting to provide support for XML-tagged structs.
- Be XPath 1.0 compliant.

**Comment by ChrisTrenkamp** [comment]
First commit is in.  Wasn't as hard as I was expecting it to be.  Let me know if you have any problems.

```
package main

import (
	"encoding/xml"
	"fmt"

	"github.com/ChrisTrenkamp/goxpath"
	"github.com/ChrisTrenkamp/goxpath/tree/xmlstruct"
)

func main() {
	str := struct {
		XMLName xml.Name `xml:"struct"`
		Elem    string   `xml:"elem"`
		Attr    string   `xml:"attr,attr"`
		Attr2   string   `xml:",attr"`
		Comm    string   `xml:",comment"`
		CD      string   `xml:",chardata"`
	}{
		Elem:  "foo",
		Attr:  "bar",
		Attr2: "baz",
		Comm:  "steak",
		CD:    "eggs",
	}

	tree := xmlstruct.MustParseStruct(&str)
	node, err := goxpath.MustParse("/struct/elem").ExecNode(tree)
	if err != nil {
		panic(err)
	}

	xmlStr, err := xml.Marshal(str)
	if err != nil {
		panic(err)
	}

	fmt.Println(string(xmlStr))

	strNode := node[0].(*xmlstruct.XMLEle)
	fmt.Println(strNode.Val.Interface())
	strNode.Val.SetString("newval")

	xmlStr, err = xml.Marshal(str)
	if err != nil {
		panic(err)
	}

	fmt.Println(string(xmlStr))
}
```

```
<struct attr="bar" Attr2="baz"><elem>foo</elem><!--steak-->eggs</struct>
foo
<struct attr="bar" Attr2="baz"><elem>newval</elem><!--steak-->eggs</struct>
```

**Comment by LeonB** [comment]
Would a custom tree also work with a custom tree-like struct? I have a struct which represents a json file and it would be nice to query that with a xpath(like) syntax.

**Comment by suntong** [comment]
@LeonB json structs are much better be queried with JPath instead of xpath. Don't know if there is Go implementation though.

**Comment by LeonB** [comment]
@suntong you're right. Thanks for pointing me to jpath!

**Comment by ChrisTrenkamp** [comment]
You can create a custom tree for any data structure, but you really should avoid using something like goxpath in your application.  If you don't care about performance or are writing a one-off program, goxpath with work fine.  However, anything beyond that, you should try writing a standard interface for your structures and use that to traverse your tree.  It'll give you better performance and compile-time safety.  On the other hand, if your structure has a crazy, non-uniform schema, goxpath can be handy, though you should still look into creating proper interfaces for your data structures.

**Comment by suntong** [comment]
This is a most valuable piece of advice that I wish I had known, but learned the hard way. It is not limited to goxpath but XPath handling as a whole. 

I need to deal with part of a complicated XML structure, and I had been avoiding writing a standard interface for the structures and use that to traverse the tree. They all worked, I was prod that I was able to dodge the bullet ever time, but because none of them can scale up easily so I was forced to choose different 3rd party libs each time. 

So eventually I bit the bullet and use chidley, to define the complicated XML structure for me. Then everything becomes so easy.

**Comment by LeonB** [comment]
I'm using it for a program that's ingesting non-structured data so I have to traverse the data at runtime. I have a Value struct that represents the data. I'm thinking about using [this path parser](https://github.com/NodePrime/jsonpath/blob/master/path.go#L150) and then using my own Value type.

**Comment by suntong** [comment]
Got carried away and forgot to close it.
